BEGIN;
CREATE TABLE IF NOT EXISTS vendors (id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL,name TEXT,created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY,vendor_id INTEGER NOT NULL REFERENCES vendors(id),name TEXT NOT NULL,sku TEXT,price NUMERIC DEFAULT 0,reorder_level INTEGER DEFAULT 0,created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS stock (id SERIAL PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),warehouse_id INTEGER,quantity INTEGER DEFAULT 0,lot_number TEXT,expiry_date DATE);
CREATE TABLE IF NOT EXISTS orders (id SERIAL PRIMARY KEY,vendor_id INTEGER NOT NULL REFERENCES vendors(id),total NUMERIC DEFAULT 0,status TEXT DEFAULT 'pending',created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS order_items (id SERIAL PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id),product_id INTEGER NOT NULL REFERENCES products(id),quantity INTEGER DEFAULT 1,unit_price NUMERIC DEFAULT 0);
COMMIT;

