// ============================================================================
// Phone & Country Data Constants
// Extracted from Auth.tsx for maintainability
// ============================================================================

export interface PhoneCodeEntry {
  code: string;
  country: string;
  flag: string;
}

export interface PhoneValidationRule {
  minLength: number;
  maxLength: number;
  example: string;
}

/** Map country name (lowercase) → phone code */
export const COUNTRY_PHONE_CODES: Record<string, string> = {
  'guinée': '+224', 'guinee': '+224', 'guinea': '+224',
  'sénégal': '+221', 'senegal': '+221',
  'mali': '+223',
  "côte d'ivoire": '+225', "cote d'ivoire": '+225', 'ivory coast': '+225',
  'burkina faso': '+226', 'burkina': '+226',
  'niger': '+227', 'togo': '+228',
  'bénin': '+229', 'benin': '+229',
  'mauritanie': '+222', 'mauritania': '+222',
  'gambie': '+220', 'gambia': '+220',
  'guinée-bissau': '+245', 'guinee bissau': '+245', 'guinea bissau': '+245',
  'cap-vert': '+238', 'cap vert': '+238', 'cape verde': '+238',
  'liberia': '+231', 'sierra leone': '+232',
  'ghana': '+233', 'nigeria': '+234',
  'cameroun': '+237', 'cameroon': '+237',
  'gabon': '+241', 'congo': '+242', 'rdc': '+243',
  'maroc': '+212', 'morocco': '+212',
  'algérie': '+213', 'algerie': '+213', 'algeria': '+213',
  'tunisie': '+216', 'tunisia': '+216',
  'france': '+33',
  'belgique': '+32', 'belgium': '+32',
  'suisse': '+41', 'switzerland': '+41',
  'canada': '+1', 'états-unis': '+1', 'etats-unis': '+1', 'usa': '+1', 'united states': '+1',
};

/** Full list of world phone codes for selector UI — ~195 countries */
export const WORLD_PHONE_CODES: PhoneCodeEntry[] = [
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫' },
  { code: '+27', country: 'Afrique du Sud', flag: '🇿🇦' },
  { code: '+355', country: 'Albanie', flag: '🇦🇱' },
  { code: '+213', country: 'Algérie', flag: '🇩🇿' },
  { code: '+49', country: 'Allemagne', flag: '🇩🇪' },
  { code: '+376', country: 'Andorre', flag: '🇦🇩' },
  { code: '+244', country: 'Angola', flag: '🇦🇴' },
  { code: '+1268', country: 'Antigua-et-Barbuda', flag: '🇦🇬' },
  { code: '+966', country: 'Arabie Saoudite', flag: '🇸🇦' },
  { code: '+54', country: 'Argentine', flag: '🇦🇷' },
  { code: '+374', country: 'Arménie', flag: '🇦🇲' },
  { code: '+61', country: 'Australie', flag: '🇦🇺' },
  { code: '+43', country: 'Autriche', flag: '🇦🇹' },
  { code: '+994', country: 'Azerbaïdjan', flag: '🇦🇿' },
  { code: '+1242', country: 'Bahamas', flag: '🇧🇸' },
  { code: '+973', country: 'Bahreïn', flag: '🇧🇭' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩' },
  { code: '+1246', country: 'Barbade', flag: '🇧🇧' },
  { code: '+32', country: 'Belgique', flag: '🇧🇪' },
  { code: '+501', country: 'Belize', flag: '🇧🇿' },
  { code: '+229', country: 'Bénin', flag: '🇧🇯' },
  { code: '+975', country: 'Bhoutan', flag: '🇧🇹' },
  { code: '+375', country: 'Biélorussie', flag: '🇧🇾' },
  { code: '+591', country: 'Bolivie', flag: '🇧🇴' },
  { code: '+387', country: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { code: '+267', country: 'Botswana', flag: '🇧🇼' },
  { code: '+55', country: 'Brésil', flag: '🇧🇷' },
  { code: '+673', country: 'Brunei', flag: '🇧🇳' },
  { code: '+359', country: 'Bulgarie', flag: '🇧🇬' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮' },
  { code: '+855', country: 'Cambodge', flag: '🇰🇭' },
  { code: '+237', country: 'Cameroun', flag: '🇨🇲' },
  { code: '+1', country: 'Canada', flag: '🇨🇦' },
  { code: '+238', country: 'Cap-Vert', flag: '🇨🇻' },
  { code: '+236', country: 'Centrafrique', flag: '🇨🇫' },
  { code: '+56', country: 'Chili', flag: '🇨🇱' },
  { code: '+86', country: 'Chine', flag: '🇨🇳' },
  { code: '+357', country: 'Chypre', flag: '🇨🇾' },
  { code: '+57', country: 'Colombie', flag: '🇨🇴' },
  { code: '+269', country: 'Comores', flag: '🇰🇲' },
  { code: '+242', country: 'Congo', flag: '🇨🇬' },
  { code: '+243', country: 'RD Congo', flag: '🇨🇩' },
  { code: '+82', country: 'Corée du Sud', flag: '🇰🇷' },
  { code: '+850', country: 'Corée du Nord', flag: '🇰🇵' },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷' },
  { code: '+225', country: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: '+385', country: 'Croatie', flag: '🇭🇷' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺' },
  { code: '+45', country: 'Danemark', flag: '🇩🇰' },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯' },
  { code: '+1767', country: 'Dominique', flag: '🇩🇲' },
  { code: '+20', country: 'Égypte', flag: '🇪🇬' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻' },
  { code: '+971', country: 'Émirats Arabes Unis', flag: '🇦🇪' },
  { code: '+593', country: 'Équateur', flag: '🇪🇨' },
  { code: '+291', country: 'Érythrée', flag: '🇪🇷' },
  { code: '+34', country: 'Espagne', flag: '🇪🇸' },
  { code: '+372', country: 'Estonie', flag: '🇪🇪' },
  { code: '+1', country: 'États-Unis', flag: '🇺🇸' },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿' },
  { code: '+251', country: 'Éthiopie', flag: '🇪🇹' },
  { code: '+679', country: 'Fidji', flag: '🇫🇯' },
  { code: '+358', country: 'Finlande', flag: '🇫🇮' },
  { code: '+33', country: 'France', flag: '🇫🇷' },
  { code: '+241', country: 'Gabon', flag: '🇬🇦' },
  { code: '+220', country: 'Gambie', flag: '🇬🇲' },
  { code: '+995', country: 'Géorgie', flag: '🇬🇪' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭' },
  { code: '+30', country: 'Grèce', flag: '🇬🇷' },
  { code: '+1473', country: 'Grenade', flag: '🇬🇩' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹' },
  { code: '+224', country: 'Guinée', flag: '🇬🇳' },
  { code: '+245', country: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: '+240', country: 'Guinée Équatoriale', flag: '🇬🇶' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾' },
  { code: '+509', country: 'Haïti', flag: '🇭🇹' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳' },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰' },
  { code: '+36', country: 'Hongrie', flag: '🇭🇺' },
  { code: '+91', country: 'Inde', flag: '🇮🇳' },
  { code: '+62', country: 'Indonésie', flag: '🇮🇩' },
  { code: '+98', country: 'Iran', flag: '🇮🇷' },
  { code: '+964', country: 'Irak', flag: '🇮🇶' },
  { code: '+353', country: 'Irlande', flag: '🇮🇪' },
  { code: '+354', country: 'Islande', flag: '🇮🇸' },
  { code: '+972', country: 'Israël', flag: '🇮🇱' },
  { code: '+39', country: 'Italie', flag: '🇮🇹' },
  { code: '+1876', country: 'Jamaïque', flag: '🇯🇲' },
  { code: '+81', country: 'Japon', flag: '🇯🇵' },
  { code: '+962', country: 'Jordanie', flag: '🇯🇴' },
  { code: '+7', country: 'Kazakhstan', flag: '🇰🇿' },
  { code: '+254', country: 'Kenya', flag: '🇰🇪' },
  { code: '+996', country: 'Kirghizistan', flag: '🇰🇬' },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮' },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰' },
  { code: '+965', country: 'Koweït', flag: '🇰🇼' },
  { code: '+856', country: 'Laos', flag: '🇱🇦' },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸' },
  { code: '+371', country: 'Lettonie', flag: '🇱🇻' },
  { code: '+961', country: 'Liban', flag: '🇱🇧' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷' },
  { code: '+218', country: 'Libye', flag: '🇱🇾' },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮' },
  { code: '+370', country: 'Lituanie', flag: '🇱🇹' },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺' },
  { code: '+389', country: 'Macédoine du Nord', flag: '🇲🇰' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬' },
  { code: '+60', country: 'Malaisie', flag: '🇲🇾' },
  { code: '+265', country: 'Malawi', flag: '🇲🇼' },
  { code: '+960', country: 'Maldives', flag: '🇲🇻' },
  { code: '+223', country: 'Mali', flag: '🇲🇱' },
  { code: '+356', country: 'Malte', flag: '🇲🇹' },
  { code: '+212', country: 'Maroc', flag: '🇲🇦' },
  { code: '+230', country: 'Maurice', flag: '🇲🇺' },
  { code: '+222', country: 'Mauritanie', flag: '🇲🇷' },
  { code: '+52', country: 'Mexique', flag: '🇲🇽' },
  { code: '+691', country: 'Micronésie', flag: '🇫🇲' },
  { code: '+373', country: 'Moldavie', flag: '🇲🇩' },
  { code: '+377', country: 'Monaco', flag: '🇲🇨' },
  { code: '+976', country: 'Mongolie', flag: '🇲🇳' },
  { code: '+382', country: 'Monténégro', flag: '🇲🇪' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲' },
  { code: '+264', country: 'Namibie', flag: '🇳🇦' },
  { code: '+674', country: 'Nauru', flag: '🇳🇷' },
  { code: '+977', country: 'Népal', flag: '🇳🇵' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮' },
  { code: '+227', country: 'Niger', flag: '🇳🇪' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬' },
  { code: '+47', country: 'Norvège', flag: '🇳🇴' },
  { code: '+64', country: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: '+968', country: 'Oman', flag: '🇴🇲' },
  { code: '+256', country: 'Ouganda', flag: '🇺🇬' },
  { code: '+998', country: 'Ouzbékistan', flag: '🇺🇿' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰' },
  { code: '+680', country: 'Palaos', flag: '🇵🇼' },
  { code: '+970', country: 'Palestine', flag: '🇵🇸' },
  { code: '+507', country: 'Panama', flag: '🇵🇦' },
  { code: '+675', country: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾' },
  { code: '+31', country: 'Pays-Bas', flag: '🇳🇱' },
  { code: '+51', country: 'Pérou', flag: '🇵🇪' },
  { code: '+63', country: 'Philippines', flag: '🇵🇭' },
  { code: '+48', country: 'Pologne', flag: '🇵🇱' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹' },
  { code: '+974', country: 'Qatar', flag: '🇶🇦' },
  { code: '+1809', country: 'République Dominicaine', flag: '🇩🇴' },
  { code: '+40', country: 'Roumanie', flag: '🇷🇴' },
  { code: '+44', country: 'Royaume-Uni', flag: '🇬🇧' },
  { code: '+7', country: 'Russie', flag: '🇷🇺' },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼' },
  { code: '+1869', country: 'Saint-Kitts-et-Nevis', flag: '🇰🇳' },
  { code: '+1758', country: 'Sainte-Lucie', flag: '🇱🇨' },
  { code: '+1784', country: 'Saint-Vincent', flag: '🇻🇨' },
  { code: '+685', country: 'Samoa', flag: '🇼🇸' },
  { code: '+378', country: 'Saint-Marin', flag: '🇸🇲' },
  { code: '+239', country: 'São Tomé-et-Príncipe', flag: '🇸🇹' },
  { code: '+221', country: 'Sénégal', flag: '🇸🇳' },
  { code: '+381', country: 'Serbie', flag: '🇷🇸' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨' },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱' },
  { code: '+65', country: 'Singapour', flag: '🇸🇬' },
  { code: '+421', country: 'Slovaquie', flag: '🇸🇰' },
  { code: '+386', country: 'Slovénie', flag: '🇸🇮' },
  { code: '+252', country: 'Somalie', flag: '🇸🇴' },
  { code: '+249', country: 'Soudan', flag: '🇸🇩' },
  { code: '+211', country: 'Soudan du Sud', flag: '🇸🇸' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { code: '+46', country: 'Suède', flag: '🇸🇪' },
  { code: '+41', country: 'Suisse', flag: '🇨🇭' },
  { code: '+597', country: 'Suriname', flag: '🇸🇷' },
  { code: '+963', country: 'Syrie', flag: '🇸🇾' },
  { code: '+992', country: 'Tadjikistan', flag: '🇹🇯' },
  { code: '+886', country: 'Taïwan', flag: '🇹🇼' },
  { code: '+255', country: 'Tanzanie', flag: '🇹🇿' },
  { code: '+235', country: 'Tchad', flag: '🇹🇩' },
  { code: '+420', country: 'Tchéquie', flag: '🇨🇿' },
  { code: '+66', country: 'Thaïlande', flag: '🇹🇭' },
  { code: '+670', country: 'Timor oriental', flag: '🇹🇱' },
  { code: '+228', country: 'Togo', flag: '🇹🇬' },
  { code: '+676', country: 'Tonga', flag: '🇹🇴' },
  { code: '+1868', country: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { code: '+216', country: 'Tunisie', flag: '🇹🇳' },
  { code: '+993', country: 'Turkménistan', flag: '🇹🇲' },
  { code: '+90', country: 'Turquie', flag: '🇹🇷' },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻' },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾' },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺' },
  { code: '+379', country: 'Vatican', flag: '🇻🇦' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳' },
  { code: '+967', country: 'Yémen', flag: '🇾🇪' },
  { code: '+260', country: 'Zambie', flag: '🇿🇲' },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼' },
];

/** Validation rules by phone code */
export const PHONE_VALIDATION_RULES: Record<string, PhoneValidationRule> = {
  '+224': { minLength: 9, maxLength: 9, example: '621234567' },
  '+221': { minLength: 9, maxLength: 9, example: '771234567' },
  '+223': { minLength: 8, maxLength: 8, example: '76123456' },
  '+225': { minLength: 10, maxLength: 10, example: '0712345678' },
  '+226': { minLength: 8, maxLength: 8, example: '70123456' },
  '+227': { minLength: 8, maxLength: 8, example: '90123456' },
  '+228': { minLength: 8, maxLength: 8, example: '90123456' },
  '+229': { minLength: 8, maxLength: 8, example: '97123456' },
  '+222': { minLength: 8, maxLength: 8, example: '22123456' },
  '+220': { minLength: 7, maxLength: 7, example: '3012345' },
  '+245': { minLength: 7, maxLength: 7, example: '9551234' },
  '+238': { minLength: 7, maxLength: 7, example: '9911234' },
  '+231': { minLength: 7, maxLength: 9, example: '770123456' },
  '+232': { minLength: 8, maxLength: 8, example: '76123456' },
  '+233': { minLength: 9, maxLength: 9, example: '241234567' },
  '+234': { minLength: 10, maxLength: 11, example: '8012345678' },
  '+237': { minLength: 9, maxLength: 9, example: '671234567' },
  '+241': { minLength: 7, maxLength: 8, example: '06123456' },
  '+242': { minLength: 9, maxLength: 9, example: '066123456' },
  '+243': { minLength: 9, maxLength: 9, example: '812345678' },
  '+212': { minLength: 9, maxLength: 9, example: '612345678' },
  '+213': { minLength: 9, maxLength: 9, example: '551234567' },
  '+216': { minLength: 8, maxLength: 8, example: '22123456' },
  '+33': { minLength: 9, maxLength: 9, example: '612345678' },
  '+32': { minLength: 9, maxLength: 9, example: '471234567' },
  '+41': { minLength: 9, maxLength: 9, example: '791234567' },
  '+1': { minLength: 10, maxLength: 10, example: '2025551234' },
  '+44': { minLength: 10, maxLength: 10, example: '7911123456' },
  '+49': { minLength: 10, maxLength: 11, example: '15123456789' },
  '+34': { minLength: 9, maxLength: 9, example: '612345678' },
  '+39': { minLength: 9, maxLength: 10, example: '3123456789' },
  '+86': { minLength: 11, maxLength: 11, example: '13123456789' },
  '+91': { minLength: 10, maxLength: 10, example: '9876543210' },
  '+81': { minLength: 10, maxLength: 10, example: '9012345678' },
  '+55': { minLength: 10, maxLength: 11, example: '11987654321' },
  '+7': { minLength: 10, maxLength: 10, example: '9123456789' },
  '+20': { minLength: 10, maxLength: 10, example: '1012345678' },
  '+27': { minLength: 9, maxLength: 9, example: '712345678' },
  '+254': { minLength: 9, maxLength: 9, example: '712345678' },
  '+255': { minLength: 9, maxLength: 9, example: '712345678' },
  '+256': { minLength: 9, maxLength: 9, example: '712345678' },
  '+250': { minLength: 9, maxLength: 9, example: '781234567' },
  '+251': { minLength: 9, maxLength: 9, example: '911234567' },
  '+971': { minLength: 9, maxLength: 9, example: '501234567' },
  '+966': { minLength: 9, maxLength: 9, example: '512345678' },
  '+90': { minLength: 10, maxLength: 10, example: '5321234567' },
};

/** Validate a phone number against its country code rules */
export function validatePhoneNumber(phone: string, code: string): boolean {
  const rule = PHONE_VALIDATION_RULES[code];
  if (!rule) {
    return phone.length >= 7 && phone.length <= 15;
  }
  return phone.length >= rule.minLength && phone.length <= rule.maxLength;
}

/** Get example phone number for a country code */
export function getPhoneExample(code: string): string {
  return PHONE_VALIDATION_RULES[code]?.example || '123456789';
}

/** Get human-readable length hint */
export function getPhoneLengthHint(code: string): string {
  const rule = PHONE_VALIDATION_RULES[code];
  if (!rule) return '7-15 chiffres';
  if (rule.minLength === rule.maxLength) return `${rule.minLength} chiffres`;
  return `${rule.minLength}-${rule.maxLength} chiffres`;
}
