# Helm values for 224Solutions Sandbox Environment
# Usage: helm install 224solutions-sandbox ./helm-chart -f k8s/sandbox/helm-values.yaml

global:
  environment: sandbox
  namespace: sandbox-pdg
  domain: sandbox.224solutions.com
  apiDomain: api-sandbox.224solutions.com

# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: 224solutions
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5173
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    NODE_ENV: sandbox
    VITE_API_URL: "http://224solutions-backend:3000"

# Backend configuration
backend:
  replicaCount: 2
  image:
    repository: 224solutions
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  env:
    NODE_ENV: sandbox
    PORT: 3000
    HOST: "0.0.0.0"

# Database configuration
postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  persistence:
    enabled: false  # Use emptyDir for sandbox
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    POSTGRES_DB: "224solutions_sandbox"
    POSTGRES_USER: "sandbox_user"
    POSTGRES_PASSWORD: "sandbox_password"

# Feature flags
featureFlags:
  ai_insights: true
  enhanced_auth: true
  financial_alerts: true
  dark_mode: true
  widget_customization: true
  sandbox_mode: true
  test_data: true
  mock_external_apis: true

# Monitoring and logging
monitoring:
  enabled: true
  logLevel: debug
  metricsEnabled: true

# Security
security:
  secretsManager:
    enabled: true
    provider: "kubernetes"  # Use K8s secrets for sandbox
  encryption:
    enabled: true
    algorithm: "aes-256-gcm"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  hosts:
    - host: sandbox.224solutions.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
    - host: api-sandbox.224solutions.com
      paths:
        - path: /
          pathType: Prefix
          service: backend

# Cron jobs
cronJobs:
  paymentsMonitor:
    enabled: true
    schedule: "0 */2 * * *"  # Every 2 hours
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  aiInsightsGenerator:
    enabled: true
    schedule: "0 */6 * * *"  # Every 6 hours
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Health checks
healthChecks:
  enabled: true
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

# Autoscaling (disabled for sandbox)
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
