// This file is automatically generated. Do not edit it directly.
// v2 - Gestion améliorée du mode hors ligne pour éviter la déconnexion
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration Supabase avec valeurs par défaut pour production
const SUPABASE_URL = 'https://uakkxaibujzxdiqzpnpr.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVha2t4YWlidWp6eGRpcXpwbnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDA2NTcsImV4cCI6MjA3NDU3NjY1N30.kqYNdg-73BTP0Yht7kid-EZu2APg9qw-b_KW9z5hJbM';

console.log('🔧 [Supabase Client] Configuration:', {
  url: SUPABASE_URL,
  keyPresent: !!SUPABASE_KEY,
  keyLength: SUPABASE_KEY?.length
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': '224solutions-web',
    },
  },
});

/**
 * Vérifie si l'app est en mode hors ligne
 */
export const isOffline = (): boolean => {
  return !navigator.onLine;
};

/**
 * Fonction pour rafraîchir manuellement la session si elle expire
 * NE PAS rafraîchir si offline pour éviter la déconnexion
 */
export const refreshSession = async () => {
  // Ne pas essayer de rafraîchir si offline
  if (isOffline()) {
    console.log('⏸️ [Supabase] Rafraîchissement ignoré - mode hors ligne');
    return null;
  }
  
  try {
    const { data, error } = await supabase.auth.refreshSession();
    if (error) {
      // Ignorer les erreurs réseau en mode offline
      if (error.message?.includes('network') || error.message?.includes('fetch')) {
        console.warn('⚠️ [Supabase] Erreur réseau ignorée (probablement offline)');
        return null;
      }
      console.error('❌ Erreur rafraîchissement session:', error);
      return null;
    }
    console.log('✅ Session rafraîchie avec succès');
    return data.session;
  } catch (e: any) {
    // Ignorer les erreurs réseau
    if (e?.message?.includes('network') || e?.message?.includes('fetch') || e?.message?.includes('Failed to fetch')) {
      console.warn('⚠️ [Supabase] Exception réseau ignorée (probablement offline)');
      return null;
    }
    console.error('❌ Exception rafraîchissement session:', e);
    return null;
  }
};

// Vérification périodique de la session (toutes les 5 minutes) - seulement si online
let sessionCheckInterval: ReturnType<typeof setInterval> | null = null;

export const startSessionMonitor = () => {
  if (sessionCheckInterval) return;
  
  sessionCheckInterval = setInterval(async () => {
    // Ne pas vérifier la session si offline pour éviter erreurs et déconnexion
    if (isOffline()) {
      console.log('⏸️ [Supabase] Vérification session ignorée - mode hors ligne');
      return;
    }
    
    try {
      const { data: { session }, error } = await supabase.auth.getSession();
      
      // Ignorer les erreurs réseau
      if (error) {
        if (error.message?.includes('network') || error.message?.includes('fetch')) {
          return;
        }
        console.warn('⚠️ [Supabase] Erreur getSession:', error.message);
        return;
      }
      
      if (session) {
        // Vérifier si le token expire dans moins de 10 minutes
        const expiresAt = session.expires_at || 0;
        const now = Math.floor(Date.now() / 1000);
        const timeUntilExpiry = expiresAt - now;
        
        if (timeUntilExpiry < 600 && timeUntilExpiry > 0) {
          console.log('⚠️ Session expire bientôt, rafraîchissement...');
          await refreshSession();
        }
      }
    } catch (e: any) {
      // Ignorer silencieusement les erreurs réseau
      if (e?.message?.includes('network') || e?.message?.includes('fetch') || e?.message?.includes('Failed to fetch')) {
        return;
      }
      console.warn('⚠️ [Supabase] Exception monitor:', e?.message);
    }
  }, 5 * 60 * 1000); // Toutes les 5 minutes
};

export const stopSessionMonitor = () => {
  if (sessionCheckInterval) {
    clearInterval(sessionCheckInterval);
    sessionCheckInterval = null;
  }
};

/**
 * Récupère la session locale sans faire d'appel réseau
 * Utile pour le mode offline
 */
export const getLocalSession = () => {
  try {
    const storageKey = `sb-uakkxaibujzxdiqzpnpr-auth-token`;
    const stored = localStorage.getItem(storageKey);
    if (stored) {
      const parsed = JSON.parse(stored);
      return parsed;
    }
  } catch (e) {
    console.warn('⚠️ [Supabase] Erreur lecture session locale:', e);
  }
  return null;
};