// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcereebvfbcehcphbayc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZXJlZWJ2ZmJjZWhjcGhiYXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTA2MzAsImV4cCI6MjA3NDIyNjYzMH0.EEbYd0xOsxR6JUz1c70iEjDH1Y98JiUYBxuIVX0KlC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});